### ISSUE TITLE
robot_localizationのodometry/gpsトピックの値がおそらく正しくない

### ISSUE THREAD

**Issue by nkm071** [hellocit/GNSS-research#1]
robot_localizationパッケージに含まれるnavsat_transform_nodeのodometry/gpsトピックの値がおそらく正しくない

**Comment by nkm071** [comment]
以下がrostopic echoの出力である．クオータニオンのwの値だけが1である．

`---
header:
  seq: 1263
  stamp:
    secs: 1703420906
    nsecs: 628080368
  frame_id: "odom"
child_frame_id: ''
pose:
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  covariance: [0.017689000000000003, -7.59710849412839e-21, 0.0, 0.0, 0.0, 0.0, 6.565395813338196e-21, 0.017689000000000003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.28302400000000005, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
twist:
  twist:
    linear:
      x: 0.0
      y: 0.0
      z: 0.0
    angular:
      x: 0.0
      y: 0.0
      z: 0.0
  covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---`

**Comment by nkm071** [comment]
原因として考えられることを以下に示す．
- 渡すべきトピックが渡されていない
- TFのリンクが適切でない
- 適切なパラメータ設定でない

**Comment by hellocit** [comment]
> test

**Comment by nkm071** [comment]
渡すべきトピックについて調査を行う．
[navsat_transform_node]()のwikiによれば，サブスクライブするトピックは以下の3個である．
- imu/data
- odometry/filtered
- gps/fix
どのトピックにも中身があることとおそらく不正な値でないことを確認した．また自分のPC側で/fixから/gps/fixにremapしたので名前にも問題がないと考える．

**Comment by nkm071** [comment]
TFのリンクについて調査した結果をまとめる．orne_box.launchでxacroやurdfを読み込んでいる．また，センサ類はそれぞれのlaunchファイル内でconfigを読み込んでいる．このことから分散実行でGNSSを起動するときは子機側でGNSSの起動を行う必要がありそうである．

現状のbox2でGNSSを使う時のlaunchファイルは以下のものを使用する．またその簡単な説明を行う．

- ナビゲーションを除くノード類の起動
[orne_box.launch](https://github.com/open-rdc/orne-box/blob/TC_2023/orne_box_bringup/launch/orne_box.launch)

- GNSSレシーバの起動
[ublox_device.launch](https://github.com/open-rdc/orne-box/blob/TC_2023/orne_box_bringup/launch/includes/ublox_device.launch)

ublow_device.launchによってGNSSレシーバは起動するが現在の構成では，TFのリンクを定義しない起動コマンドを用いている．従って，TFのリンクが適切でないという結論でbox2内で真偽を調査する．

**Comment by nkm071** [comment]
パラメータについて
おそらくこの[ファイル](https://github.com/open-rdc/orne-box/blob/TC_2023/orne_box_bringup/launch/includes/robot_localization.launch)を見る必要がありそう．

**Comment by nkm071** [comment]
https://github.com/open-rdc/orne-box/issues/96
上記issueで対応するためこちらのissueを閉じる
