### ISSUE TITLE
オフセットをどのようにするか

### ISSUE THREAD

**Issue by nkm071** [hellocit/GNSS-research#2]
自己位置推定の誤差を算出する際のオフセットをどのようにするか
使用するトピックと値
- amcl_pose
- 緯度と経度
二つのトピックは単純に引き算してよいのか不明なので検討する

**Comment by nkm071** [comment]
端的にいうとz軸上から見た時にGNSSの取り付け位置とamcl_poseは一致しているかどうか

**Comment by nkm071** [comment]
GNSSの取り付け位置がbase_linkから見てどれほどずれているかの補正をかける必要があるかもしれない．シミュレータで表示される中心はどこかでどこから見たものかは変わる．

**Comment by nkm071** [comment]
[このサイト](https://memo.soarcloud.com/ros%E3%81%AE%E5%BA%A7%E6%A8%99%E5%A4%89%E6%8F%9Btf%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6/)のlaser_linkとbase_linkの図が分かりやすい．ロボットの上から見た時xとy座標は同一でないのでそのオフセットの計算が必要

**Comment by nkm071** [comment]
しかし計算の後処理の工程なのでひとまず先送り

**Comment by yasuohayashibara** [comment]
確かにbase_linkどうしを計算しなくてはならないので面倒ですね．
簡単に処理するためにはGNSSアンテナをbase_linkがあると思われる上に近づけると良いかもしれません．
後は，URDFにGNSSの位置を記載して，tfの機能を使用してbase_linkの位置に変換してもらうという方法がありますが，やや面倒ですね．
現在のシステムがどのようになっているのか十分に理解していないので適切なアドバイスかどうか分かりませんが．．．

できれば，現在のシステムのシステム図を示してもらえるともっと適格なアドバイスができると思います．
どちらにしても必要になると思いますので．

**Comment by nkm071** [comment]
ありがとうございます．
そうですね現在のシステムのシステム図を作成するのでお待ちください．

**Comment by nkm071** [comment]
![Screenshot from 2023-12-29 18-59-23](https://github.com/hellocit/GNSS-research/assets/91714744/991dd056-d426-436a-9c0b-e7b2faaf71da)

おそらく上記の写真が最もわかりやすい．gazeboだが．．．GNSSの取り付け位置はgnss_linkであることは確定している．しかし，amcl_poseはどのリンクに一致しているかは不明

**Comment by nkm071** [comment]
上記のシミュレータを立ち上げた時のtfツリーのグラフ
![output](https://github.com/hellocit/GNSS-research/assets/91714744/2f882cba-d81d-40ba-afb7-1fd3949029d4)

**Comment by nkm071** [comment]
https://github.com/hellocit/GNSS-research/blob/main/test/test.py

上記にchatgptに「ROSのtf2においてあるリンク間のxとy座標の差を求めてください．pythonでお願いします．

」という命令で作成させたスクリプト

**Comment by nkm071** [comment]
https://github.com/open-rdc/orne-box/issues/97

orne-boxの方にあげた

**Comment by nkm071** [comment]
計算はできたのでひとまず閉じる
