### ISSUE TITLE
座標系をどのように合わせるか

### ISSUE THREAD

**Issue by nkm071** [hellocit/GNSS-research#3]
緯度と経度を平面直角座標系に直したものと自己位置推定の結果を何も補正せず，差を出してよいのかどうか

**Comment by nkm071** [comment]
そもそも原点合わせしていないもので差をだせないのでは？

**Comment by yasuohayashibara** [comment]
そのとおりです．
原点を合わせる必要があります．
原点合わせをROSで行う方法もありますが，ミス無く行うためにはROS内での処理を十分に理解しなければなりません．
おそらくある程度ソースコードを読んで理解する必要があると思います．

計測後に行ったほうがミスが少なく楽だと思います．

**Comment by nkm071** [comment]
承知しました．ありがとうございます．

こちらに関しては，後回しにしますが一つの案を示します．アドバイスいただければと思います．

[山本先輩のリポジトリ](https://github.com/taishiyamamoto/gnss_initpose_ros)は測位により得られた経緯度からUTM座標を取得し，任意の座標を原点として座標変換するためのものです．

**Comment by yasuohayashibara** [comment]
時間があればいろいろと考えることはできると思いますが，あまり時間が無いと思いますので，以下を並べて人の目で合わせるとかいう感じになると思います．

１）GNSSで得た座標
２）LiDARとジャイロオドメトリの自己位置推定の座標

**Comment by nkm071** [comment]
1)についてプロットしたものを示します．経緯度を入力にしました．
![image](https://github.com/hellocit/GNSS-research/assets/91714744/748e962a-9c0d-440e-b9c2-067072576fe1)
2)についてプロットしたものを作成します．取得したデータを座標変換する方法がわからないのでgoogle spread sheetと格闘しています．

**Comment by nkm071** [comment]
![image](https://github.com/hellocit/GNSS-research/assets/91714744/2a800168-de3a-4c01-a14c-56275b1beb0f)
おそらく上記です．

**Comment by nkm071** [comment]
だいぶ異なるように見えます．
[csvデータ](https://drive.google.com/drive/folders/16VTLPZvG8Pb6aCaDtJeTcLLaZHSRaJjy)

**Comment by yasuohayashibara** [comment]
どこを基準にするのかという問題はありますが，GNSSの出力が正しいとすると，その差が自己位置推定の誤差になります．

**Comment by nkm071** [comment]
ありがとうございます．上記で行った方法で誤差を求めようとしましたが二つの問題点があり，詰まりました．

一つ目に二つの座標系をどのように重ね合わせればよいかということです．二つ目に，お互いのトピックの周期が異なるためにデータを線形補間する必要があります．

一つ目は，経緯度のx,y座標のデータと自己位置推定のx,y座標のデータの方位合わせを行っていないため，差を求めたとしても意味がありません．imuからの方位を用いて方位合わせができるかもしれませんが調査していません．

二つ目は，経緯度のエクセルのデータの総量が2416個でamcl_poseのデータの総量が1200個です．このことから一つ目の問題を解決したとしてもデータの総量が異なるため差が求めれられません．解決策としては線形補間という方法を用いることで解決できる可能性があります．

以上，アドバイスよろしくお願いします．

## 提案
一応，山本先輩のrosパッケージを用いればこれら二つの問題を解決できます．noetic環境で動作することは確認しましたがconfigファイルの設定がわからず，所望の動作は得られていません．

## 感想
rosbagの便利さを思い知った．

## 参考文献
[経緯度とamcl_poseの差を求めようとしたエクセル](https://docs.google.com/spreadsheets/d/1lI2oFcVbZA3DBbow-XeTDfE3B5H93B1t/edit?usp=sharing&ouid=101675091294276560995&rtpof=true&sd=true)

[山本先輩のrosパッケージ](https://github.com/taishiyamamoto/gnss_initpose_ros)

**Comment by yasuohayashibara** [comment]
できるだけ一致するように合わせてみました．
傾向が似ているのはありますが，あまりにもズレすぎているので，データの取得方法になにか問題があるかもしれません．
ちなみに，自己位置推定は問題なくできていそうでしたか？
目で見てズレているようでしたら，取り直したほうが良いと思います．

![image](https://github.com/hellocit/GNSS-research/assets/5755200/f835440a-8334-4136-b18e-6efb21796a13)

[caluculation.xlsx](https://github.com/hellocit/GNSS-research/files/13933573/caluculation.xlsx)

**Comment by nkm071** [comment]
ありがとうございます．確かに自己位置推定のプロットがあまりにもずれていると思います．データを取り直してみます．

**Comment by nkm071** [comment]
加えて，質問です．[こちらのissue](https://github.com/open-rdc/orne-box/issues/97)で示したTFのオフセットはまだ対応できていないのですがそれには対処せずにデータを集めることを優先しても構いませんか？

**Comment by yasuohayashibara** [comment]
はい．
優先順位を決めて進めたほうが良いと思います．

**Comment by nkm071** [comment]
こちらもう使用しないと思うのでissueをクローズします
