### ISSUE TITLE
マップの位置とGNSSの値がどれほどあっているか不明

### ISSUE THREAD

**Issue by nkm071** [hellocit/GNSS-research#4]
以前の問題点にてマップの位置とGNSSからの位置がずれている時に誤差の修正方法で研究が変わり得るというアドバイスを頂いた．現在の測位結果とマップのずれがどれほどあるかの確認は必要かどうか．雑に画面と場所の写真は撮った．

**Comment by yasuohayashibara** [comment]
すでに行っていたと思いますが，地図にGNSSの測地データを重ねてある程度問題が無いことを確認したほうが良いと思います．
見て問題がなさそうであれば，GNSSの値は正しいと仮定しても良いと思います．

道に沿って移動したのに，道から外れるなどあれば，再検討する必要があると思います．

**Comment by nkm071** [comment]
google mapに緯度と経度をプロットしたもの
![image](https://github.com/hellocit/GNSS-research/assets/91714744/bb5622d5-61ee-455f-90b3-01a253b61908)

**Comment by nkm071** [comment]
box2が置かれた場所
![image](https://github.com/hellocit/GNSS-research/assets/91714744/63b97e50-5cac-4df3-8493-54e5b48907c5)

rvizの画面
![image](https://github.com/hellocit/GNSS-research/assets/91714744/a0de235c-b58b-4f41-a0f4-2113aaf2cce1)

**Comment by nkm071** [comment]
おそらく問題がないのでissueを閉じます．
